<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
data(Prestige, package="car")
```

```{r}
summary(Prestige)
```


```{r}
local({
  .Table <- with(Prestige, table(type))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
```

```{r}
scatterplotMatrix(~education+income+prestige+women, reg.line=FALSE, 
  smooth=FALSE, spread=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  id.n=0, diagonal = 'histogram', data=Prestige)
```

```{r}
scatterplotMatrix(~education+income+prestige+women, reg.line=FALSE, 
  smooth=FALSE, spread=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  id.n=0, diagonal = 'histogram', data=Prestige)
```

```{r}
scatterplotMatrix(~education+income+prestige+women, reg.line=FALSE, 
  smooth=TRUE, spread=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  id.n=0, diagonal = 'histogram', data=Prestige)
```

```{r}
scatterplotMatrix(~education+income+prestige+women, reg.line=FALSE, 
  smooth=TRUE, spread=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), 
  id.n=0, diagonal = 'histogram', data=Prestige)
```

```{r}
Prestige$log2income <- with(Prestige, log2(income))
```

```{r}
RegModel.1 <- lm(prestige~education+log2income+women, data=Prestige)
summary(RegModel.1)
```

```{r}
RegModel.2 <- lm(prestige~education+log2income+women, data=Prestige)
summary(RegModel.2)
```

```{r}
oldpar <- par(oma=c(0,0,3,0), mfrow=c(2,2))
```


```{r}
plot(RegModel.2)
```


```{r}
par(oldpar)
```



